/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "meetmaker-ipc.pb-c.h"
void   badoo__meetmaker__ipc__ipc_client_request__init
                     (Badoo__Meetmaker__Ipc__IpcClientRequest         *message)
{
  static Badoo__Meetmaker__Ipc__IpcClientRequest init_value = BADOO__MEETMAKER__IPC__IPC_CLIENT_REQUEST__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_client_request__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_client_request__pack
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_client_request__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcClientRequest *
       badoo__meetmaker__ipc__ipc_client_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcClientRequest *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_client_request__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_client_request__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcClientRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_client_response__init
                     (Badoo__Meetmaker__Ipc__IpcClientResponse         *message)
{
  static Badoo__Meetmaker__Ipc__IpcClientResponse init_value = BADOO__MEETMAKER__IPC__IPC_CLIENT_RESPONSE__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_client_response__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_client_response__pack
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_client_response__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcClientResponse *
       badoo__meetmaker__ipc__ipc_client_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcClientResponse *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_client_response__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_client_response__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcClientResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_client_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_reindex_cities__init
                     (Badoo__Meetmaker__Ipc__IpcReindexCities         *message)
{
  static Badoo__Meetmaker__Ipc__IpcReindexCities init_value = BADOO__MEETMAKER__IPC__IPC_REINDEX_CITIES__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_reindex_cities__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_reindex_cities__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_reindex_cities__pack
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_reindex_cities__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_reindex_cities__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_reindex_cities__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcReindexCities *
       badoo__meetmaker__ipc__ipc_reindex_cities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcReindexCities *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_reindex_cities__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_reindex_cities__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcReindexCities *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_reindex_cities__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_snapshot_sync_state__init
                     (Badoo__Meetmaker__Ipc__IpcSnapshotSyncState         *message)
{
  static Badoo__Meetmaker__Ipc__IpcSnapshotSyncState init_value = BADOO__MEETMAKER__IPC__IPC_SNAPSHOT_SYNC_STATE__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__pack
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *
       badoo__meetmaker__ipc__ipc_snapshot_sync_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_snapshot_sync_state__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_e2s_port__init
                     (Badoo__Meetmaker__Ipc__IpcE2sPort         *message)
{
  static Badoo__Meetmaker__Ipc__IpcE2sPort init_value = BADOO__MEETMAKER__IPC__IPC_E2S_PORT__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_e2s_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_e2s_port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_e2s_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_e2s_port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_e2s_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_e2s_port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcE2sPort *
       badoo__meetmaker__ipc__ipc_e2s_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcE2sPort *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_e2s_port__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_e2s_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcE2sPort *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_e2s_port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_s2s_port__init
                     (Badoo__Meetmaker__Ipc__IpcS2sPort         *message)
{
  static Badoo__Meetmaker__Ipc__IpcS2sPort init_value = BADOO__MEETMAKER__IPC__IPC_S2S_PORT__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_s2s_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_s2s_port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_s2s_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_s2s_port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_s2s_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_s2s_port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcS2sPort *
       badoo__meetmaker__ipc__ipc_s2s_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcS2sPort *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_s2s_port__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_s2s_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcS2sPort *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_s2s_port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_rsyncd_port__init
                     (Badoo__Meetmaker__Ipc__IpcRsyncdPort         *message)
{
  static Badoo__Meetmaker__Ipc__IpcRsyncdPort init_value = BADOO__MEETMAKER__IPC__IPC_RSYNCD_PORT__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcRsyncdPort *
       badoo__meetmaker__ipc__ipc_rsyncd_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcRsyncdPort *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_rsyncd_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcRsyncdPort *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   badoo__meetmaker__ipc__ipc_msg__init
                     (Badoo__Meetmaker__Ipc__IpcMsg         *message)
{
  static Badoo__Meetmaker__Ipc__IpcMsg init_value = BADOO__MEETMAKER__IPC__IPC_MSG__INIT;
  *message = init_value;
}
size_t badoo__meetmaker__ipc__ipc_msg__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t badoo__meetmaker__ipc__ipc_msg__pack
                     (const Badoo__Meetmaker__Ipc__IpcMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t badoo__meetmaker__ipc__ipc_msg__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Badoo__Meetmaker__Ipc__IpcMsg *
       badoo__meetmaker__ipc__ipc_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Badoo__Meetmaker__Ipc__IpcMsg *)
     protobuf_c_message_unpack (&badoo__meetmaker__ipc__ipc_msg__descriptor,
                                allocator, len, data);
}
void   badoo__meetmaker__ipc__ipc_msg__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &badoo__meetmaker__ipc__ipc_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_client_request__field_descriptors[4] =
{
  {
    .name              = "ctx_id",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT64,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientRequest, ctx_id),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "gpbrpc_pointer",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT64,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientRequest, gpbrpc_pointer),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "msg_id",
    .id                = 3,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientRequest, msg_id),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "request",
    .id                = 4,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_BYTES,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientRequest, request),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_client_request__field_indices_by_name[] = {
  0,   /* field[0] = ctx_id */
  1,   /* field[1] = gpbrpc_pointer */
  2,   /* field[2] = msg_id */
  3,   /* field[3] = request */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_client_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_client_request__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_client_request",
  .short_name            = "IpcClientRequest",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcClientRequest",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcClientRequest),
  .n_fields              = 4,
  .fields                = badoo__meetmaker__ipc__ipc_client_request__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_client_request__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_client_request__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_client_request__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_client_response__field_descriptors[3] =
{
  {
    .name              = "ctx_id",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT64,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientResponse, ctx_id),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "msg_id",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientResponse, msg_id),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "response",
    .id                = 4,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_BYTES,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcClientResponse, response),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_client_response__field_indices_by_name[] = {
  0,   /* field[0] = ctx_id */
  1,   /* field[1] = msg_id */
  2,   /* field[2] = response */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_client_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_client_response__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_client_response",
  .short_name            = "IpcClientResponse",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcClientResponse",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcClientResponse),
  .n_fields              = 3,
  .fields                = badoo__meetmaker__ipc__ipc_client_response__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_client_response__field_indices_by_name,
  .n_field_ranges        = 2,
  .field_ranges          = badoo__meetmaker__ipc__ipc_client_response__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_client_response__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_reindex_cities__field_descriptors[1] =
{
  {
    .name              = "cities",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_BYTES,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcReindexCities, cities),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_reindex_cities__field_indices_by_name[] = {
  0,   /* field[0] = cities */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_reindex_cities__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_reindex_cities__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_reindex_cities",
  .short_name            = "IpcReindexCities",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcReindexCities",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcReindexCities),
  .n_fields              = 1,
  .fields                = badoo__meetmaker__ipc__ipc_reindex_cities__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_reindex_cities__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_reindex_cities__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_reindex_cities__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_snapshot_sync_state__field_descriptors[1] =
{
  {
    .name              = "position",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcSnapshotSyncState, position),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_snapshot_sync_state__field_indices_by_name[] = {
  0,   /* field[0] = position */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_snapshot_sync_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_snapshot_sync_state",
  .short_name            = "IpcSnapshotSyncState",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcSnapshotSyncState",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcSnapshotSyncState),
  .n_fields              = 1,
  .fields                = badoo__meetmaker__ipc__ipc_snapshot_sync_state__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_snapshot_sync_state__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_snapshot_sync_state__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_snapshot_sync_state__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_e2s_port__field_descriptors[3] =
{
  {
    .name              = "shard_id_bind",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcE2sPort, shard_id_bind),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "event_id_connect",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcE2sPort, event_id_connect),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "port",
    .id                = 3,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcE2sPort, port),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_e2s_port__field_indices_by_name[] = {
  1,   /* field[1] = event_id_connect */
  2,   /* field[2] = port */
  0,   /* field[0] = shard_id_bind */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_e2s_port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_e2s_port__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_e2s_port",
  .short_name            = "IpcE2sPort",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcE2sPort",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcE2sPort),
  .n_fields              = 3,
  .fields                = badoo__meetmaker__ipc__ipc_e2s_port__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_e2s_port__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_e2s_port__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_e2s_port__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_s2s_port__field_descriptors[3] =
{
  {
    .name              = "shard_id_bind",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcS2sPort, shard_id_bind),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "shard_id_connect",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcS2sPort, shard_id_connect),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "port",
    .id                = 3,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcS2sPort, port),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_s2s_port__field_indices_by_name[] = {
  2,   /* field[2] = port */
  0,   /* field[0] = shard_id_bind */
  1,   /* field[1] = shard_id_connect */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_s2s_port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_s2s_port__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_s2s_port",
  .short_name            = "IpcS2sPort",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcS2sPort",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcS2sPort),
  .n_fields              = 3,
  .fields                = badoo__meetmaker__ipc__ipc_s2s_port__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_s2s_port__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_s2s_port__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_s2s_port__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_rsyncd_port__field_descriptors[2] =
{
  {
    .name              = "shard_id",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcRsyncdPort, shard_id),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
  {
    .name              = "port",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_UINT32,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcRsyncdPort, port),
    .descriptor        = NULL,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_rsyncd_port__field_indices_by_name[] = {
  1,   /* field[1] = port */
  0,   /* field[0] = shard_id */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_rsyncd_port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_rsyncd_port",
  .short_name            = "IpcRsyncdPort",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcRsyncdPort",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcRsyncdPort),
  .n_fields              = 2,
  .fields                = badoo__meetmaker__ipc__ipc_rsyncd_port__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_rsyncd_port__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_rsyncd_port__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_rsyncd_port__init,
};
static const ProtobufCFieldDescriptor badoo__meetmaker__ipc__ipc_msg__field_descriptors[8] =
{
  {
    .name              = "msg_type",
    .id                = 1,
    .label             = PROTOBUF_C_LABEL_REQUIRED,
    .type              = PROTOBUF_C_TYPE_ENUM,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, msg_type),
    .descriptor        = &badoo__meetmaker__ipc__msg_type__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "client_request",
    .id                = 2,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, client_request),
    .descriptor        = &badoo__meetmaker__ipc__ipc_client_request__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "client_response",
    .id                = 3,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, client_response),
    .descriptor        = &badoo__meetmaker__ipc__ipc_client_response__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "reindex_cities",
    .id                = 4,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, reindex_cities),
    .descriptor        = &badoo__meetmaker__ipc__ipc_reindex_cities__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "snapshot_sync_state",
    .id                = 5,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, snapshot_sync_state),
    .descriptor        = &badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "e2s_port",
    .id                = 6,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, e2s_port),
    .descriptor        = &badoo__meetmaker__ipc__ipc_e2s_port__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "s2s_port",
    .id                = 7,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, s2s_port),
    .descriptor        = &badoo__meetmaker__ipc__ipc_s2s_port__descriptor,
    .default_value     = NULL,
  },
  {
    .name              = "rsyncd_port",
    .id                = 8,
    .label             = PROTOBUF_C_LABEL_OPTIONAL,
    .type              = PROTOBUF_C_TYPE_MESSAGE,
    .quantifier_offset = 0,
    .offset            = PROTOBUF_C_OFFSETOF(Badoo__Meetmaker__Ipc__IpcMsg, rsyncd_port),
    .descriptor        = &badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor,
    .default_value     = NULL,
  },
};
static const unsigned badoo__meetmaker__ipc__ipc_msg__field_indices_by_name[] = {
  1,   /* field[1] = client_request */
  2,   /* field[2] = client_response */
  5,   /* field[5] = e2s_port */
  0,   /* field[0] = msg_type */
  3,   /* field[3] = reindex_cities */
  7,   /* field[7] = rsyncd_port */
  6,   /* field[6] = s2s_port */
  4,   /* field[4] = snapshot_sync_state */
};
static const ProtobufCIntRange badoo__meetmaker__ipc__ipc_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_msg__descriptor =
{
  .magic                 = PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  .name                  = "badoo.meetmaker.ipc.ipc_msg",
  .short_name            = "IpcMsg",
  .c_name                = "Badoo__Meetmaker__Ipc__IpcMsg",
  .package_name          = "badoo.meetmaker.ipc",
  .sizeof_message        = sizeof(Badoo__Meetmaker__Ipc__IpcMsg),
  .n_fields              = 8,
  .fields                = badoo__meetmaker__ipc__ipc_msg__field_descriptors,
  .fields_sorted_by_name = badoo__meetmaker__ipc__ipc_msg__field_indices_by_name,
  .n_field_ranges        = 1,
  .field_ranges          = badoo__meetmaker__ipc__ipc_msg__number_ranges,
  .message_init          = (ProtobufCMessageInit) badoo__meetmaker__ipc__ipc_msg__init,
};
const ProtobufCEnumValue badoo__meetmaker__ipc__msg_type__enum_values_by_number[15] =
{
  { "IPC_CLIENT_REQUEST", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_CLIENT_REQUEST", 1 },
  { "IPC_CLIENT_RESPONSE", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_CLIENT_RESPONSE", 2 },
  { "IPC_REINDEX_CITIES", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_REINDEX_CITIES", 3 },
  { "IPC_REOPEN_LOG", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_REOPEN_LOG", 4 },
  { "IPC_SNAPSHOT_SYNC_ACQUIRE", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_ACQUIRE", 5 },
  { "IPC_SNAPSHOT_SYNC_RELEASE", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_RELEASE", 6 },
  { "IPC_SNAPSHOT_SYNC_STATE", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_STATE", 7 },
  { "IPC_E2S_PORT", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_E2S_PORT", 8 },
  { "IPC_S2S_PORT", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_S2S_PORT", 9 },
  { "IPC_RSYNCD_PORT", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_RSYNCD_PORT", 10 },
  { "IPC_READY_E2S_CONNECTED", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_E2S_CONNECTED", 11 },
  { "IPC_READY_S2S_CONNECTED", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_S2S_CONNECTED", 12 },
  { "IPC_READY_BMPID_INDEXES_CREATED", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_BMPID_INDEXES_CREATED", 13 },
  { "IPC_READY_STORAGE_SYNC", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_STORAGE_SYNC", 14 },
  { "IPC_READY_TO_RUN", "BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_TO_RUN", 15 },
};
static const ProtobufCIntRange badoo__meetmaker__ipc__msg_type__value_ranges[] = {
{1, 0},{0, 15}
};
const ProtobufCEnumValueIndex badoo__meetmaker__ipc__msg_type__enum_values_by_name[15] =
{
  { "IPC_CLIENT_REQUEST", 0 },
  { "IPC_CLIENT_RESPONSE", 1 },
  { "IPC_E2S_PORT", 7 },
  { "IPC_READY_BMPID_INDEXES_CREATED", 12 },
  { "IPC_READY_E2S_CONNECTED", 10 },
  { "IPC_READY_S2S_CONNECTED", 11 },
  { "IPC_READY_STORAGE_SYNC", 13 },
  { "IPC_READY_TO_RUN", 14 },
  { "IPC_REINDEX_CITIES", 2 },
  { "IPC_REOPEN_LOG", 3 },
  { "IPC_RSYNCD_PORT", 9 },
  { "IPC_S2S_PORT", 8 },
  { "IPC_SNAPSHOT_SYNC_ACQUIRE", 4 },
  { "IPC_SNAPSHOT_SYNC_RELEASE", 5 },
  { "IPC_SNAPSHOT_SYNC_STATE", 6 },
};
const ProtobufCEnumDescriptor badoo__meetmaker__ipc__msg_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "badoo.meetmaker.ipc.msg_type",
  "msg_type",
  "Badoo__Meetmaker__Ipc__MsgType",
  "badoo.meetmaker.ipc",
  15,
  badoo__meetmaker__ipc__msg_type__enum_values_by_number,
  15,
  badoo__meetmaker__ipc__msg_type__enum_values_by_name,
  1,
  badoo__meetmaker__ipc__msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
