/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_meetmaker_2dipc_2eproto__INCLUDED
#define PROTOBUF_C_meetmaker_2dipc_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Badoo__Meetmaker__Ipc__IpcClientRequest Badoo__Meetmaker__Ipc__IpcClientRequest;
typedef struct _Badoo__Meetmaker__Ipc__IpcClientResponse Badoo__Meetmaker__Ipc__IpcClientResponse;
typedef struct _Badoo__Meetmaker__Ipc__IpcReindexCities Badoo__Meetmaker__Ipc__IpcReindexCities;
typedef struct _Badoo__Meetmaker__Ipc__IpcSnapshotSyncState Badoo__Meetmaker__Ipc__IpcSnapshotSyncState;
typedef struct _Badoo__Meetmaker__Ipc__IpcE2sPort Badoo__Meetmaker__Ipc__IpcE2sPort;
typedef struct _Badoo__Meetmaker__Ipc__IpcS2sPort Badoo__Meetmaker__Ipc__IpcS2sPort;
typedef struct _Badoo__Meetmaker__Ipc__IpcRsyncdPort Badoo__Meetmaker__Ipc__IpcRsyncdPort;
typedef struct _Badoo__Meetmaker__Ipc__IpcMsg Badoo__Meetmaker__Ipc__IpcMsg;


/* --- enums --- */

typedef enum _Badoo__Meetmaker__Ipc__MsgType {
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_CLIENT_REQUEST = 1,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_CLIENT_RESPONSE = 2,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_REINDEX_CITIES = 3,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_REOPEN_LOG = 4,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_ACQUIRE = 5,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_RELEASE = 6,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_SNAPSHOT_SYNC_STATE = 7,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_E2S_PORT = 8,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_S2S_PORT = 9,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_RSYNCD_PORT = 10,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_E2S_CONNECTED = 11,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_S2S_CONNECTED = 12,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_BMPID_INDEXES_CREATED = 13,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_STORAGE_SYNC = 14,
  BADOO__MEETMAKER__IPC__MSG_TYPE__IPC_READY_TO_RUN = 15
} Badoo__Meetmaker__Ipc__MsgType;

/* --- messages --- */

struct  _Badoo__Meetmaker__Ipc__IpcClientRequest
{
  ProtobufCMessage base;
  uint64_t ctx_id;
  uint64_t gpbrpc_pointer;
  uint32_t msg_id;
  ProtobufCBinaryData request;
};
#define BADOO__MEETMAKER__IPC__IPC_CLIENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_client_request__descriptor) \
    , 0, 0, 0, {0,NULL} }


struct  _Badoo__Meetmaker__Ipc__IpcClientResponse
{
  ProtobufCMessage base;
  uint64_t ctx_id;
  uint32_t msg_id;
  ProtobufCBinaryData response;
};
#define BADOO__MEETMAKER__IPC__IPC_CLIENT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_client_response__descriptor) \
    , 0, 0, {0,NULL} }


struct  _Badoo__Meetmaker__Ipc__IpcReindexCities
{
  ProtobufCMessage base;
  ProtobufCBinaryData cities;
};
#define BADOO__MEETMAKER__IPC__IPC_REINDEX_CITIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_reindex_cities__descriptor) \
    , {0,NULL} }


struct  _Badoo__Meetmaker__Ipc__IpcSnapshotSyncState
{
  ProtobufCMessage base;
  uint32_t position;
};
#define BADOO__MEETMAKER__IPC__IPC_SNAPSHOT_SYNC_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor) \
    , 0 }


struct  _Badoo__Meetmaker__Ipc__IpcE2sPort
{
  ProtobufCMessage base;
  uint32_t shard_id_bind;
  uint32_t event_id_connect;
  uint32_t port;
};
#define BADOO__MEETMAKER__IPC__IPC_E2S_PORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_e2s_port__descriptor) \
    , 0, 0, 0 }


struct  _Badoo__Meetmaker__Ipc__IpcS2sPort
{
  ProtobufCMessage base;
  uint32_t shard_id_bind;
  uint32_t shard_id_connect;
  uint32_t port;
};
#define BADOO__MEETMAKER__IPC__IPC_S2S_PORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_s2s_port__descriptor) \
    , 0, 0, 0 }


struct  _Badoo__Meetmaker__Ipc__IpcRsyncdPort
{
  ProtobufCMessage base;
  uint32_t shard_id;
  uint32_t port;
};
#define BADOO__MEETMAKER__IPC__IPC_RSYNCD_PORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor) \
    , 0, 0 }


struct  _Badoo__Meetmaker__Ipc__IpcMsg
{
  ProtobufCMessage base;
  Badoo__Meetmaker__Ipc__MsgType msg_type;
  Badoo__Meetmaker__Ipc__IpcClientRequest *client_request;
  Badoo__Meetmaker__Ipc__IpcClientResponse *client_response;
  Badoo__Meetmaker__Ipc__IpcReindexCities *reindex_cities;
  Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *snapshot_sync_state;
  Badoo__Meetmaker__Ipc__IpcE2sPort *e2s_port;
  Badoo__Meetmaker__Ipc__IpcS2sPort *s2s_port;
  Badoo__Meetmaker__Ipc__IpcRsyncdPort *rsyncd_port;
};
#define BADOO__MEETMAKER__IPC__IPC_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&badoo__meetmaker__ipc__ipc_msg__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


/* Badoo__Meetmaker__Ipc__IpcClientRequest methods */
void   badoo__meetmaker__ipc__ipc_client_request__init
                     (Badoo__Meetmaker__Ipc__IpcClientRequest         *message);
size_t badoo__meetmaker__ipc__ipc_client_request__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest   *message);
size_t badoo__meetmaker__ipc__ipc_client_request__pack
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_client_request__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcClientRequest   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcClientRequest *
       badoo__meetmaker__ipc__ipc_client_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_client_request__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcClientRequest *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcClientResponse methods */
void   badoo__meetmaker__ipc__ipc_client_response__init
                     (Badoo__Meetmaker__Ipc__IpcClientResponse         *message);
size_t badoo__meetmaker__ipc__ipc_client_response__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse   *message);
size_t badoo__meetmaker__ipc__ipc_client_response__pack
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_client_response__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcClientResponse   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcClientResponse *
       badoo__meetmaker__ipc__ipc_client_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_client_response__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcClientResponse *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcReindexCities methods */
void   badoo__meetmaker__ipc__ipc_reindex_cities__init
                     (Badoo__Meetmaker__Ipc__IpcReindexCities         *message);
size_t badoo__meetmaker__ipc__ipc_reindex_cities__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities   *message);
size_t badoo__meetmaker__ipc__ipc_reindex_cities__pack
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_reindex_cities__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcReindexCities   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcReindexCities *
       badoo__meetmaker__ipc__ipc_reindex_cities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_reindex_cities__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcReindexCities *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcSnapshotSyncState methods */
void   badoo__meetmaker__ipc__ipc_snapshot_sync_state__init
                     (Badoo__Meetmaker__Ipc__IpcSnapshotSyncState         *message);
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState   *message);
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__pack
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_snapshot_sync_state__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *
       badoo__meetmaker__ipc__ipc_snapshot_sync_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_snapshot_sync_state__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcE2sPort methods */
void   badoo__meetmaker__ipc__ipc_e2s_port__init
                     (Badoo__Meetmaker__Ipc__IpcE2sPort         *message);
size_t badoo__meetmaker__ipc__ipc_e2s_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort   *message);
size_t badoo__meetmaker__ipc__ipc_e2s_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_e2s_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcE2sPort   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcE2sPort *
       badoo__meetmaker__ipc__ipc_e2s_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_e2s_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcE2sPort *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcS2sPort methods */
void   badoo__meetmaker__ipc__ipc_s2s_port__init
                     (Badoo__Meetmaker__Ipc__IpcS2sPort         *message);
size_t badoo__meetmaker__ipc__ipc_s2s_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort   *message);
size_t badoo__meetmaker__ipc__ipc_s2s_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_s2s_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcS2sPort   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcS2sPort *
       badoo__meetmaker__ipc__ipc_s2s_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_s2s_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcS2sPort *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcRsyncdPort methods */
void   badoo__meetmaker__ipc__ipc_rsyncd_port__init
                     (Badoo__Meetmaker__Ipc__IpcRsyncdPort         *message);
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort   *message);
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__pack
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_rsyncd_port__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcRsyncdPort   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcRsyncdPort *
       badoo__meetmaker__ipc__ipc_rsyncd_port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_rsyncd_port__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcRsyncdPort *message,
                      ProtobufCAllocator *allocator);
/* Badoo__Meetmaker__Ipc__IpcMsg methods */
void   badoo__meetmaker__ipc__ipc_msg__init
                     (Badoo__Meetmaker__Ipc__IpcMsg         *message);
size_t badoo__meetmaker__ipc__ipc_msg__get_packed_size
                     (const Badoo__Meetmaker__Ipc__IpcMsg   *message);
size_t badoo__meetmaker__ipc__ipc_msg__pack
                     (const Badoo__Meetmaker__Ipc__IpcMsg   *message,
                      uint8_t             *out);
size_t badoo__meetmaker__ipc__ipc_msg__pack_to_buffer
                     (const Badoo__Meetmaker__Ipc__IpcMsg   *message,
                      ProtobufCBuffer     *buffer);
Badoo__Meetmaker__Ipc__IpcMsg *
       badoo__meetmaker__ipc__ipc_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   badoo__meetmaker__ipc__ipc_msg__free_unpacked
                     (Badoo__Meetmaker__Ipc__IpcMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Badoo__Meetmaker__Ipc__IpcClientRequest_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcClientRequest *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcClientResponse_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcClientResponse *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcReindexCities_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcReindexCities *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcSnapshotSyncState_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcSnapshotSyncState *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcE2sPort_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcE2sPort *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcS2sPort_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcS2sPort *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcRsyncdPort_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcRsyncdPort *message,
                  void *closure_data);
typedef void (*Badoo__Meetmaker__Ipc__IpcMsg_Closure)
                 (const Badoo__Meetmaker__Ipc__IpcMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    badoo__meetmaker__ipc__msg_type__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_client_request__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_client_response__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_reindex_cities__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_snapshot_sync_state__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_e2s_port__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_s2s_port__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_rsyncd_port__descriptor;
extern const ProtobufCMessageDescriptor badoo__meetmaker__ipc__ipc_msg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_meetmaker_2dipc_2eproto__INCLUDED */
